name: CD Workflow for Angular

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Use Windows to access network drive

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Network Drive
        run: |
          net use Z: "${{ secrets.NET_DRIVE_PATH }}" /user:${{ secrets.NET_DRIVE_USERNAME }} ${{ secrets.NET_DRIVE_PASSWORD }}
          robocopy E-EstateV2/dist/e-estate-v2 Z:\e-estate-v2 /MIR
          net use Z: /delete
