name: CD Workflow for Angular

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Ensure Windows compatibility for network drive commands

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Network Access
        shell: cmd
        run: |
          ping DEVAPP02
          net view \\DEVAPP02

      - name: Access folder E-EstateV2 and Build
        run: |
          # Navigate to the E-EstateV2 directory
          cd E-EstateV2

          # Install dependencies
          npm install

          # Install Angular CLI
          npm install -g @angular/cli

          # Test Karma
          # ng test

          # Build Angular project
          ng build


      - name: Verify Build Path
        shell: pwsh
        run: |
          if (-Not (Test-Path "E-EstateV2\dist\e-estate-v2")) { 
            Write-Error "Build folder not found!" 
            exit 1 
          }

      - name: Verify Network Drive
        shell: cmd
        run: |
          net use Z: "${{ secrets.NET_DRIVE_PATH }}" /user:${{ secrets.NET_DRIVE_USERNAME }} ${{ secrets.NET_DRIVE_PASSWORD }}
          if %ERRORLEVEL% NEQ 0 exit 1
          
      - name: Map Network Drive and Copy Files
        shell: cmd
        run: |
          net use Z: "${{ secrets.NET_DRIVE_PATH }}" /user:${{ secrets.NET_DRIVE_USERNAME }} ${{ secrets.NET_DRIVE_PASSWORD }}
          robocopy "E-EstateV2\dist\e-estate-v2" "Z:\e-estate-v2" /MIR
          net use Z: /delete
