name: CD Workflow for Angular

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Ensure Windows compatibility for network drive commands

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Angular App
        run: |
          cd E-EstateV2
          npm install
          ng build --configuration=production --output-path=dist/e-estate-v2


      - name: Verify Build Path
        shell: pwsh
        run: |
          if (-Not (Test-Path "E-EstateV2\dist\e-estate-v2")) { 
            Write-Error "Build folder not found!" 
            exit 1 
          }

      - name: Map Network Drive and Copy Files
        shell: cmd
        run: |
          net use Z: "${{ secrets.NET_DRIVE_PATH }}" /user:${{ secrets.NET_DRIVE_USERNAME }} ${{ secrets.NET_DRIVE_PASSWORD }}
          robocopy "E-EstateV2\dist\e-estate-v2" "Z:\e-estate-v2" /MIR
          net use Z: /delete
