name: CD Workflow for Angular

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Use Windows to access network drive

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Network Drive
        run: |
          net use "\\DEVAPP02\trainingE-estate" /user:${{ secrets.NET_DRIVE_USERNAME }} ${{ secrets.NET_DRIVE_PASSWORD }}
          robocopy "C:\Users\sabariah\OneDrive - LEMBAGA GETAH MALAYSIA\Desktop\e-Estate2024\e-Estate2024\E-EstateV2\dist\e-estate-v2" "\\DEVAPP02\trainingE-estate" /MIR
          net use "\\DEVAPP02\trainingE-estate" /delete
