name: CD Workflow for Angular

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Windows required for network drive access

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Angular App
        run: |
          cd E-EstateV2
          npm install
          npm install -g @angular/cli
          ng build

      - name: Verify Build Path
        run: |
          if not exist "E-EstateV2\dist\e-estate-v2" exit 1

      - name: Deploy to Network Location
        run: |
          net use Z: "\\DEVAPP02\trainingE-estate" /user:${{ secrets.NET_DRIVE_USERNAME }} ${{ secrets.NET_DRIVE_PASSWORD }}
          robocopy E-EstateV2\dist\e-estate-v2 Z:\e-estate-v2 /MIR
          net use Z: /delete
